version: "3"
services:
  web:
    image: richarvey/nginx-php-fpm:latest
    container_name: ${APP_NAME:?err}-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      # - ./vendor:/var/www/html/vendor
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    links:
      - maria
    environment:
      - HIDE_NGINX_HEADERS=1
      - ERRORS=1
      - PHP_ERRORS_STDERR=1
      - DOMAIN=vcap.me
      - SKIP_COMPOSER=1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APP_NAME:?err}-phpmyadmin
    ports:
      - "1234:80"
    links:
      - maria
    environment:
      PMA_HOST: maria

  maria:
    image: mariadb:latest
    container_name: ${APP_NAME:?err}-maria
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/maria
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress

  wordpress:
    image: wordpress
    container_name: ${APP_NAME:?err}-wordpress
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: maria
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./public:/var/www/html

volumes:
  mariadb_data:

networks:
  default:
